name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            install: sudo apt-get update && sudo apt-get install -y build-essential
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC Dev Environment
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install dependencies
        run: ${{ matrix.install }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Format
        run: cargo fmt --check
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Clippy
        run: cargo clippy --release --all-targets --all-features -- -D warnings
        if: ${{ matrix.os == 'macos-latest' }}

      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release